on:
  push:
    tags:
      - "v*"

jobs:
  release_image:
    runs-on: ubuntu-latest

    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - uses: actions/checkout@v6 # Update-worthy.

      - id: meta
        uses: docker/metadata-action@v5 # Update-worthy.
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: type=semver,pattern={{version}}

      - uses: docker/login-action@v3 # Update-worthy.
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3 # Update-worthy.

      - id: build_push
        uses: docker/build-push-action@v6 # Update-worthy.
        with:
          context: .
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - uses: actions/attest-build-provenance@v3 # Update-worthy.
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.build_push.outputs.digest }}
          push-to-registry: true
